# If false, player appears at spawn.
custom_location: false

# If custom_location is set to true
CustomLocationTrue:
    # Can be "world", "world_nether", "world_the_end"
    world: "world"
    X: 0.0
    Y: 60.0
    Z: 0.0
    Yaw: 0.0
    Pitch: 0.0

# Session time in seconds.
session_time: 300

# Timeout in seconds. Set -1 to disable:
timeout: 60    

# If true, player cannot move if not authorized.
disable_moving: false

# Permissions to revoke for the time of authorization
permissions:
    # Permissions listed here will be set to false and then back to true.
    for_everyone:
        - "minecraft.command.msg"
    # Permissions listed here will be set to false and then back to true
    # only if the user has this permission set to true.
    # Otherwise nothing will be done to the user.
    if_true:
        