name: TrueAuth
author: ArkadSt
version: 1.1
main: org.trueauth.Main
api-version: 1.16
depend: [LuckPerms]

commands:
    register:
        description: "TrueAuth provided command."
        usage: "§cUsage: /register password password"
        aliases: reg
    login:
        description: "TrueAuth provided command."
        usage: "§cUsage: /login password"
        aliases: l
    changepassword:
        description: "TrueAuth provided command."
        usage: "§cUsage: /changepassword new_password new_password"
        aliases: changepass
    trueauth:
        description: "TrueAuth provided command."
        permission: trueauth.admin
